<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>
<!-- форма ввода e-mail для аутентификации -->
<?php if (!isset($correctUser)): ?>
    <form action="/session" method="post">
      <div>
        <label>
          Введите ваш E-mail:    
          <input type="email" required name="email" value="">
        </label>
      </div>
      <input type="submit" value="Sign In">
    </form>
<?php else: ?>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">    
          <div>
          Добро пожаловать,
          <?= $correctUser['nickname'] . "!" ?></div>
          <input type="submit" value="Sign Out">
         </div>   
    </form>
<?php endif ?>
<!-- END -->