<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
             <div><?= $message ?></div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>

<p><a href="/users/new">Добавить пользователя</a></p>
<table>
  <?php foreach ($users as $key => $user): ?>
    <tr>
      <td>
          <?= $key ?>
      </td>
      <td>
          <?= $user['nickname'] ?>
      </td>
      <td>
          <?= $user['email'] ?>
      </td>
      <td>
          <?= $user['id'] ?>
      </td>
    </tr>
  <?php endforeach ?>
</table>